version: '3.8'


services:

  api:
    build: ./api
    container_name: api_c
    ports: 
      - '8000:8000'
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

#  nginx:
#    depends_on:
#      - api
#      - frontend
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - "3000:80"